services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./sqlite:/usr/src/app/sqlite
      - ./main.py:/usr/src/app/main.py
