services:
  api:
    build: .
    volumes:
      - ./sqlite:/usr/src/app/sqlite

  caddy:
    image: caddy:2.8.4-alpine
    restart: always
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
