services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --no-server-header
    volumes:
      - ./sqlite:/code/sqlite
    restart: unless-stopped

  caddy:
    image: caddy:2.8.4-alpine
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
